# Generated by Django 5.1.4 on 2025-02-04 22:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Webapp', '0002_registrationdb'),
    ]

    operations = [
        migrations.CreateModel(
            name='CartDb',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(default=True, max_length=50, null=True)),
                ('productname', models.CharField(default=True, max_length=50, null=True)),
                ('quantity', models.IntegerField(default=True, null=True)),
                ('totalprice', models.IntegerField(default=True, null=True)),
            ],
        ),
    ]
